-- CreateTable
CREATE TABLE `ApplianceIn` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `deviceID` VARCHAR(191) NOT NULL,
    `assocID` VARCHAR(191) NOT NULL,
    `imageUrl` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
